apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: dev-uniandes
spec:
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      serviceAccountName: ksa-convert-api
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - name: api
        image: us-east4-docker.pkg.dev/convertor-tool/convert-repo/convert-api:v4.8
        env:
          - name: proyect-id
            value: convertor-tool
          - name: file-topic
            value: file_topic
          - name: email-topic
            value: email_topic
          - name: upload-bucket-name
            value: original-song
          - name: download-bucket-name
            value: convert-song
          - name: zone
            value: us-east4
          - name: instance_name
            value: tool-conversion
          - name: db_user
            value: postgres
          - name: db_password
            value: root
          - name: db_name
            value: tool-conversion-3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: api-load-balancer
  namespace: dev-uniandes
spec:
  type: LoadBalancer
  selector:
    role: api
  ports:
  - port: 5001
    targetPort: 5001