apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: dev-uniandes
spec:
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      serviceAccountName: ksa-convert-api
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - name: api
        image: gcr.io/conversiontoolg34/apiconvert:v1.8
        env:
          - name: proyect-id
            value: conversiontoolg34
          - name: file-topic
            value: file-topic
          - name: email-topic
            value: email-topic
          - name: upload-bucket-name
            value: original-song-v1
          - name: download-bucket-name
            value: convert-song-v1
          - name: zone
            value: us-east4
          - name: instance_name
            value: tool-conversion
          - name: db_user
            value: postgres
          - name: db_password
            value: root
          - name: db_name
            value: tool-conversion-v1
        resources:
          requests:
            memory: "2048Mi"
            cpu: "300m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: api-load-balancer
  namespace: dev-uniandes
spec:
  type: LoadBalancer
  selector:
    role: api
  ports:
  - port: 5001
    targetPort: 5001