apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster
spec:
  selector:
    matchLabels:
      role: kafka-cluster
  template:
    metadata:
      labels:
        role: kafka-cluster
    spec:
      containers:
      - name: kafka-cluster
        image: confluentinc/cp-kafka:6.2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-cluster:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-cluster:29092,PLAINTEXT_HOST://kafka-cluster:9092
        ports:
          - containerPort: 9092
          - containerPort: 9101
            
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
spec:
  selector:
    role: kafka-cluster
  ports:
  - port: 9092
    name: kafka-t1
    targetPort: 9092
  - port: 9101
    name: kafka-t2
    targetPort: 9101