apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: DATABASE_HOST
            value: 127.0.0.1
          - name: POSTGRES_USER
            value: root
          - name: POSTGRES_PASSWORD
            value: admin
          - name: POSTGRES_DB
            value: tool-conversion
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    role: postgres
  ports:
  - port: 5432
    targetPort: 5432

