version: '2'
services:
  api:
    build: ./api
    ports:
      - 5001:5001
    stdin_open: true # Allows us to run the container in interactive mode
    volumes:
      - ./uploads:/python-docker/uploads
    #deploy:
     # resources:
      #  limits:
       #   cpus: '2'
        #  memory: 2G
        #reservations:
         # cpus: '2'
          #memory: 2G
    #depends_on:
     # - kafka
      #- postgres
    #networks:
     # - broker-kafka

  k6:
    image: grafana/k6
    volumes:
      - ./tests:/scripts
    environment:
      - K6_CLOUD_TOKEN=d256a37fd84a464e8e8a87e92031bed882f08fb10ed6414a4f3c7473624eed38
    networks:
      - broker-kafka

  convert:
    build:
      context: ./convert
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    volumes:
      - ./uploads/uploads:/convert/app/uploads
      - ./uploads/process:/convert/app/process
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    networks:
      - broker-kafka
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://10.128.0.6:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  postgres:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tool-conversion
    ports: 
      - 5432:5432
    networks:
      - broker-kafka

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on: 
      - postgres
    networks:
      - broker-kafka

networks:
  broker-kafka:
    driver: bridge
