apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-convert-api
#https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#proxy
#https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_on_cluster