service: convert-api
runtime: python
env: flex
service_account: api-project-759687602744@appspot.gserviceaccount.com
env_variables:
  download_bucket_name: convert-song-v1
  upload_bucket_name: original-song-v1
  project_id: api-project-759687602744
  file_topic_name: file-topic
  email_topic_name: email-topic
  zone: us-east4
  instance_name: convert-tool-v2
  db_user: postgres
  db_password: root
  db_name: tool-conversion-v1
automatic_scaling:
  max_num_instances: 3
  min_num_instances: 1
  cpu_utilization:
    target_utilization: 0.5
resources:
  cpu: 1
  memory_gb: 1
runtime_config:
  python_version: 3